export const UPDATE_BOOKS = "UPDATE_BOOKS";

export const ADD_TO_BOOKSHELF = "ADD_TO_BOOKSHELF";
export const ADD_MULTIPLE_TO_BOOKSHELF = "ADD_MULTIPLE_TO_BOOKSHELF";
export const REMOVE_FROM_BOOKSHELF = "REMOVE_FROM_BOOKSHELF";
export const CLEAR_BOOKSHELF = "CLEAR_BOOKSHELF";
export const UPDATE_BOOKSHELF_QUANTITY = "UPDATE_BOOKSHELF_QUANTITY";
export const TOGGLE_BOOKSHELF = "TOGGLE_BOOKSHELF";

// export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
// export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";